// <auto-generated />
using System;
using BeerReview.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerReview.Migrations
{
    [DbContext(typeof(BeerReviewContext))]
    [Migration("20220316201142_Tertiary")]
    partial class Tertiary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BeerReview.Models.Beer", b =>
                {
                    b.Property<int>("BeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ABV")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BeerId");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("BeerReview.Models.BeerDrinker", b =>
                {
                    b.Property<int>("BeerDrinkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<int>("DrinkerId")
                        .HasColumnType("int");

                    b.HasKey("BeerDrinkerId");

                    b.HasIndex("BeerId");

                    b.HasIndex("DrinkerId");

                    b.ToTable("BeerDrinker");
                });

            modelBuilder.Entity("BeerReview.Models.Drinker", b =>
                {
                    b.Property<int>("DrinkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("SignUp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DrinkerId");

                    b.ToTable("Drinkers");
                });

            modelBuilder.Entity("BeerReview.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DrinkerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ReviewId");

                    b.HasIndex("BeerId");

                    b.HasIndex("DrinkerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BeerReview.Models.BeerDrinker", b =>
                {
                    b.HasOne("BeerReview.Models.Beer", "Beer")
                        .WithMany("JoinEntities")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerReview.Models.Drinker", "Drinker")
                        .WithMany("JoinEntities")
                        .HasForeignKey("DrinkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Drinker");
                });

            modelBuilder.Entity("BeerReview.Models.Review", b =>
                {
                    b.HasOne("BeerReview.Models.Beer", "Beer")
                        .WithMany("Reviews")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerReview.Models.Drinker", "Drinker")
                        .WithMany("Reviews")
                        .HasForeignKey("DrinkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Drinker");
                });

            modelBuilder.Entity("BeerReview.Models.Beer", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BeerReview.Models.Drinker", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
